In [18]:
import numpy as np
from numpy import linalg as la

def T(x,y,z):
    return [x-y+z , 2*x+3*y-(1/2)*z, x+y-2*z]

B1 = np.array([[-1,1,0],[5,-1,2],[1,2,1]])
B2 = np.array([[1,1,0],[0,0,1],[1,5,2]])
print(B1[1])

w1 = T(-1,1,0)
w2 = T(5,-1,2)
w3 = T(1,2,1)
print(w1,w2,w3)

v1 = la.solve(B2.T,w1)
v2 = la.solve(B2.T,w2)
v3 = la.solve(B2.T,w3)
M = np.array([v2,v2,v3])
display(M.T)


    

[ 5 -1  2]
[-2, 1.0, 0] [8, 6.0, 0] [0, 7.5, 1]


array([[ 8.5  ,  8.5  , -1.875],
       [ 1.   ,  1.   , -2.75 ],
       [-0.5  , -0.5  ,  1.875]])

In [19]:
from sympy import Matrix
import numpy as np
from numpy import linalg as la

def T(x,y,z):
    return [x-y+z , 2*x+3*y-(1/2)*z, x+y-2*z]

def Mat(T,a1,a2,a3,b1,b2,b3):    
    B1 = np.array([a1,a2,a3])
    B2 = np.array([b1,b2,b3])
    print("the specified basis for the domain space is\n",(B1))
    print("the specified basis for the co-domain space is\n", B2)
    
    c1,c2,c3 = B1[0]
    d1,d2,d3 = B1[1]
    e1,e2,e3 = B1[2]

    w1 = T(c1,c2,c3)
    w2 = T(d1,d2,d3)
    w3 = T(e1,e2,e3)
    print("evaluating T at the vectors of basis B1",w1,w2,w3)

    v1 = la.solve(B2.T,w1)
    v2 = la.solve(B2.T,w2)
    v3 = la.solve(B2.T,w3)
    M = np.array([v1,v2,v3])
    display(Matrix(M.T))

Mat(T,[-1,1,0],[5,-1,2],[1,2,1],[1,1,0],[0,0,1],[1,5,2])

the specified basis for the domain space is
 [[-1  1  0]
 [ 5 -1  2]
 [ 1  2  1]]
the specified basis for the co-domain space is
 [[1 1 0]
 [0 0 1]
 [1 5 2]]
evaluating T at the vectors of basis B1 [-2, 1.0, 0] [8, 6.0, 0] [0, 7.5, 1]


Matrix([
[-2.75,  8.5, -1.875],
[ -1.5,  1.0,  -2.75],
[ 0.75, -0.5,  1.875]])

In [20]:
from sympy import symbols,Matrix,solve
import numpy as np

a,c1,c2,x,y = symbols('a c1 c2 x y')
A = Matrix([[2,3],[4,-5]])

u1 = np.array([1,-1])
u2 = np.array([1,1])
v1 = np.array([1,0])
v2 = np.array([0,1])

T0 = [A[0,0]*v1,A[1,0]*v2]
T1 = [A[0,1]*v1,A[1,1]*v2]

sumT0 = T0[0]+T0[1]
sumT1 = T1[0]+T1[1]
print("the images of the ordered basis vectors in b1 under the transformation are ",sumT0,sumT1)


eq = np.array([u1[0]*c1+u2[0*c2],u1[1]*c1+u2[1]*c2])
p,q = eq[0], eq[1]
a = solve((p-x,q-y),c1,c2,dict=True)
c1,c2 = a[0][c1],a[0][c2]
print("the coordinate of the vector with respect to the b1 are",c1,"and",c2)

t = sumT0*c1+sumT1*c2
print("the linear transformation of T is T(x,y)= ",tuple(t))


the images of the ordered basis vectors in b1 under the transformation are  [2 4] [3 -5]
the coordinate of the vector with respect to the b1 are x - 1 and x + y - 1
the linear transformation of T is T(x,y)=  (5*x + 3*y - 5, -x - 5*y + 1)
